### ISSUE TITLE
BFormSpinButton lacks default sizing

### ISSUE THREAD

**Issue by dpash** [bootstrap-vue-next/bootstrap-vue-next#2156]
### Describe the bug

Test case:

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-spinbutton.html#sizing

The default size for BFormSpinButton is smaller than `sm` size. There's no `.form-control-md` class but the standard `.form-control` doesn't size the spin button correctly.

I've used the following scoped css in my component to get it roughly the right size. This is mostly half way between `.form-control-sm` and `.form-control-lg` but I'm sure only some of these properties are needed.

```css
#spinbutton {
    min-height: calc(1.5em + 0.75 + calc(var(--bs-border-width) * 2));
    padding: 0.375rem 0.75rem;
    font-size: 0.92rem;
    border-radius: var(--bs-border-radius);
}
```

### Reproduction

https://stackblitz.com/edit/github-fnvgqz?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
